project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - projects.qmd
      - presentations.qmd
      - extrapage.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true



editor: visual
